ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS Desconto_Padrao DECIMAL(10,2) DEFAULT 10.00,
ADD COLUMN IF NOT EXISTS Permite_Desconto TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS Tipo_Desconto VARCHAR(1) DEFAULT 'P' COMMENT 'P = Percentual, V = Valor';

-- 2. ALTERAR TABELA pedidos
-- Adiciona campos de desconto do pedido
ALTER TABLE pedidos 
ADD COLUMN IF NOT EXISTS ValorTotalSemDesconto DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS ValorTotalComDesconto DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS TipoDesconto VARCHAR(1) DEFAULT NULL COMMENT 'P = Percentual, V = Valor',
ADD COLUMN IF NOT EXISTS ValorDesconto DECIMAL(10,2) DEFAULT 0.00;